# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

use_frameworks!

pod 'SwiftLint'

target 'NYTimes' do

end

#def test_pods
#  pod 'Quick'
#  pod 'Nimble'
#end
#
target 'NYTimesTests' do
  pod 'Quick'
  pod 'Nimble'
end
